# Generated by Django 6.0.1 on 2026-01-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_brand_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
