# Generated by Django 6.0.1 on 2026-02-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleinvetory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinvetory',
            old_name='vehicles_value',
            new_name='vehicles_price',
        ),
    ]
