# Generated by Django 6.0.1 on 2026-02-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_vehicles_value_vehicleinvetory_vehicles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
